spring:
  application:
    name: authorization-server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/vault"
    password: "admin"
    username: "vault_user"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 800
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtRgYb/r1u4afROnUC1SG
          lyuA9b2kBji4gL8z8f9xRgC+vB3czOJMTTNMCL+d+mr1EYv6M7G3b9DaxqTcVPoR
          ZIe5DbkFhtipz8x1qccTOhaxTpMCnX12je0pJR/FaqysQI/VqkOuBBsw03O/ETc1
          14/oS0k8Y+6vpDPxsvHQRSY/zb1Mjs0JIqdvU4sajIHOXZdOnB9FfC3TD0mc1Ur/
          xyRSBgEvLyrw9IfEih1Ql4KLYF8L99XZ6tXe2j9W9WhipQNE10/acunoRYFAcKG8
          +8tD0SZTvWZvCZRbRZKotcT8h8voRMIOaHHWHPHCVUbR0zFM+jYtv4wh2a9aCz89
          xwIDAQAB
          -----END PUBLIC KEY-----